const mock = {
    storeName: 'Trader',
    logoUrl: '/assets/images/logo.png',
    menuOptions: [
        'Homens',
        'Mulheres',
        'Acessórios',
        'Bolsas',
        'Sapatos'
    ],
    lastStories: [
        { title: 'Lançamentos de Blusas', img: 'https://source.unsplash.com/random/200x200?sig=1' },
        { title: 'Novas Bolsas Gulci', img: 'https://source.unsplash.com/random/200x200?sig=2' },
        { title: 'Promoção Shorts Femininos', img: 'https://source.unsplash.com/random/200x200?sig=3' }
    ],
    products: [
        { title: 'Lorem ipsum inceptos eros', images: ['https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig='], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', value: 120 },
        { title: 'Lorem ipsum inceptos eros', images: ['https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig='], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', value: 120 },
        { title: 'Lorem ipsum inceptos eros', images: ['https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig='], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', value: 120 },
        { title: 'Lorem ipsum inceptos eros', images: ['https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig='], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', value: 120 },
        { title: 'Lorem ipsum inceptos eros', images: ['https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig='], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', value: 120 },
        { title: 'Lorem ipsum inceptos eros', images: ['https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig='], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', value: 120 },
        { title: 'Lorem ipsum inceptos eros', images: ['https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig='], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', value: 120 },
        { title: 'Lorem ipsum inceptos eros', images: ['https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig=', 'https://source.unsplash.com/random/600x800?sig='], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', value: 120 },
    ]
}

export default mock